#%RAML 1.0 DataType
properties:
  FirstName:
    type: string
    required: true
  LastName:
    type: string
    required: true
  Email:
    type: string
    required: false
  Address:
    type: string
    required: false

